# Workflow to unit test on push
name: Unit Tests

# Trigger the workflow on push or pull request,
on:
  push:
    branches: "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  # Job to run unit tests
  test:
    # Ubuntu as the virtual machine because it is the most common
    runs-on: ubuntu-latest

    # Steps to complete the job
    steps:
      - name: Check Chrome Errors
        run: |
          google-chrome --version
          chromedriver --version
          google-chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &> chrome_output.txt || cat chrome_output.txt

      - name: Display Chrome Output
        run: cat chrome_output.txt

      # Checkout the code
      - name: Get Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      # Install dependancies
      - name: Install Dependancies
        run: npm install

      # Run unit tests
      - name: Run Unit Tests
        run: npm test

      # Display test results
      - name: Output Github Information
        run: echo " ${{ toJSON(github) }}"

      # Upload test report
      - name: Test Report 
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: Test Report
            path: report/
