# Workflow to unit test on push
name: Unit Tests

# Trigger the workflow on push to main branch
on:
  push:
    branches: "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  # Job to run unit tests
  test:
    # Ubuntu as the virtual machine because it is the most common
    runs-on: ubuntu-latest

    # Steps to complete the job
    steps:
      # Checkout the code
      - name: Get Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      # Install dependancies
      - name: Install Dependancies
        run: npm install

      # Run unit tests
      - name: Run Unit Tests
        run: npm test

      # Display test results
      - name: Output Github Information
        run: echo " ${{ toJSON(github) }}"
